### ISSUE TITLE
Fix docs

### ISSUE THREAD

**Issue by doubret** [rstiller/inspector-vm#1]
Example in the docs is wrong :
`const memoryMetrics: V8MemoryMetrics = new V8MemoryMetrics("v8", registry.getDefaultClock());`
should be :
`const memoryMetrics: V8MemoryMetrics = new V8MemoryMetrics("v8");`

`V8MemoryMetrics` constructor doesn't take a `clock` argument.

Also, example uses deprecated `registry.register` method instead of `registry.registerMetric`.

**Comment by rstiller** [comment]
Fixed the examples and some typos in the comments.
Also included https://github.com/rstiller/inspector-vm/pull/2 in the new version I just published: 3.2.0
Feel free to reopen the ticket if I missed anything.

**Comment by doubret** [comment]
Everything works like a charm now.
